export const fortuneArr: string[] = [
  "집보다 나은 곳은 없습니다.",
  "오늘 만큼은 오직 마음이 이끄는 대로 하세요.",
  "가끔은 일부러 길을 잃어보세요.",
  "믿음은 사랑의 가장 중요한 조건입니다.",
  "결국에는 모두 괜찮아질 거예요.",
  "두려워하지 마세요. 죽기밖에 더 하겠어요?",
  "해야 할 일을 하세요.",
  "당연한 말이지만, 실패가 없으면 성공도 없습니다.",
  "여행자의 시선으로 일상을 살아가보세요.",
  "5분 동안만 20년 뒤의 당신을 떠올려보세요.",
  "평소의 당신과 반대로 행동해보세요.",
  "아무런 대가 없이 누군가를 도와보세요.",
  "이틀 전 아침에는 뭘 먹었나요?",
  "당신이 감사해야 할 사람들을 떠올려보세요.",
  "오늘 밤엔 예전에 좋아하던 영화를 다시 한번 관람해보면 어떨까요?",
  "누군가에게 찾아온 행운을 진심으로 축하해보세요. 당신에게도 그런 행운이 찾아올지 모릅니다.",
];

export const fortuneEngArr: string[] = [
  "There's no place like home.",
  "Just follow your heart.",
  "Sometimes, purposely get lost.",
  "Trust is the most important condition for love.",
  "Eventually, everything will be okay.",
  "Don't be afraid. What more can you do other than die?",
  "Do what you have to do.",
  "It goes without saying, but without failure, there is no success.",
  "Experience everyday life from the perspective of a traveler.",
  "Take a moment to envision yourself 20 years from now.",
  "Act opposite to your usual self.",
  "Help someone without expecting anything in return.",
  "What did you eat for breakfast two days ago?",
  "Think of the people you should be grateful for.",
  "How about watching a movie you used to love tonight?",
  "Sincerely congratulate someone who has encountered good luck. You never know, such luck might come to you too.",
];
